name: ${project.name}
main: ${project.groupId}.noGrief
version: ${project.version}
api-version: 1.13
description: ${project.description}
author: thatguy
commands:
  nogrief:
    usage: /nogrief <item> [on|off]
    description: change grief status.
    aliases: [ng]
permissions:
  nogrief.command.admin:
    default: op


